#! /bin/sh
#
# Builds and installs libiconv for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

echo "--- BEGIN: crossbuild_zlib ---"

cd /tmp

wget --output-document=/tmp/zlib.tar.gz ${ZLIB_URL}

if [ -f zlib.tar.gz ]; then

	if [ ! -d zlib ]; then 
		mkdir zlib
	fi

	tar -zxf zlib.tar.gz -C zlib
	cd zlib/*
else
	echo "crossbuild_zlib failed: Could not get/extract zlib source"
	exit 1
fi

if [ -f configure ]; then
	./configure\
		--host=${HOST_TRIPLET}\
		--prefix=/usr/${HOST_TRIPLET}
else
	echo "crossbuild_libiconv failed: Could not find ./configure (is libiconv source tarball sane?)"
	exit 1
fi

if [ -f Makefile ]; then
	make
#	make install
else
	echo "crossbuild_libiconv failed: Could not find Makefile (did ./configure fail?)"
	exit 1
fi

echo "--- END: crossbuild_libiconv ---"