#! /bin/sh
#
# Builds and installs libsndfile for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBSNDFILE_URL
#
# Specifies the URL of the libsndfile source tarball you want to use.
export LIBSNDFILE_URL="http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.25.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libsndfile ---"

basic_autotools_lib libsndfile "${LIBSNDFILE_URL}" gz ""

echo "--- END: crossbuild_libsndfile ---"
echo "*************************************************************************"
