#! /bin/sh
#
# Builds and installs libogg for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBOGG_URL
#
# Specifies the URL of the libogg source tarball you want to use.
export LIBOGG_URL="http://downloads.xiph.org/releases/ogg/libogg-1.3.0.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libogg ---"

basic_autotools_lib libogg "${LIBOGG_URL}" gz ""

echo "--- END: crossbuild_libogg ---"
echo "*************************************************************************"
