#! /bin/sh
#
# Builds and installs libiconv for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBICONV_URL
#
# Specifies the URL of the libiconv source tarball you want to use.
export LIBICONV_URL="https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libiconv ---"

basic_autotools_lib libiconv "${LIBICONV_URL}" gz ""

echo "--- END: crossbuild_libiconv ---"
echo "*************************************************************************"
