#! /bin/sh
#
# Builds and installs libglm for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBGLM_URL
#
# Specifies the URL of the libglm source tarball you want to use.
export LIBGLM_URL="https://sourceforge.net/projects/ogl-math/files/glm-0.9.4.4/glm-0.9.4.4.zip/download"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libglm ---"

get_zipball libglm ${LIBGLM_URL}
if [ ${?} -eq 10 ]
then
	echo "crossbuild_libglm failed: Could not get/extract libglm source"
	exit 1
fi

cd ${SRC_ROOT_DIR}/libglm/*

if [ -d glm ]
then
	echo "Installing libglm"
	cp -R glm /usr/${HOST_TRIPLET}/include/

else
	echo "crossbuild_libglm failed: Could not find glm directory (is the libglm source tarball sane?)"
	exit 1
fi

echo "--- END: crossbuild_libglm ---"
echo "*************************************************************************"
