#! /bin/sh
#@DEP@ zlib
#
# Builds and installs libpng for the cross toolchain.
# Executed by build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBPNG_URL
#
# Specifies the URL of the libpng source tarball you want to use.
export LIBPNG_URL="https://prdownloads.sourceforge.net/libpng/libpng-1.6.34.tar.xz?download"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libpng ---"

basic_autotools_lib libpng "${LIBPNG_URL}" xz ""

echo "--- END: crossbuild_libpng ---"
echo "*************************************************************************"
