#! /bin/sh
#@DEP@ libogg
#
# Builds and installs libvorbis for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBVORBIS_URL
#
# Specifies the URL of the libvorbis source tarball you want to use.
export LIBVORBIS_URL="http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.3.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libvorbis ---"

basic_autotools_lib libvorbis ${LIBVORBIS_URL} gz ""

echo "--- END: crossbuild_libvorbis ---"
echo "*************************************************************************"
