#! /bin/sh
#
# Builds and installs libfreetype for the cross toolchain.
# Executed by build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBFREETYPE_URL
#
# Specifies the URL of the libfreetype source tarball you want to use.
export LIBFREETYPE_URL="https://download.savannah.gnu.org/releases/freetype/freetype-2.5.3.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libfreetype ---"

get_tarball libfreetype "${LIBFREETYPE_URL}" gz
if [ ${?} -eq 10 ]
then
	echo "crossbuild_libfreetype failed: Could not get/extract libfreetype source"
	exit 1
fi

# We do this twice, once for shared libs and once for static libs.
cmake_build ${SRC_ROOT_DIR}/libfreetype/* "-DBUILD_SHARED_LIBS:BOOL=true"
cmake_build ${SRC_ROOT_DIR}/libfreetype/* "-DBUILD_SHARED_LIBS:BOOL=false"

echo "--- END: crossbuild_libfreetype ---"
echo "*************************************************************************"
