#! /bin/sh
#@DEP@ zlib
#
# Builds and installs libpng for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBPNG_URL
#
# Specifies the URL of the libpng source tarball you want to use.
export LIBPNG_URL="ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.15.tar.xz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libpng ---"

basic_autotools_lib libpng "${LIBPNG_URL}" xz ""

echo "--- END: crossbuild_libpng ---"
echo "*************************************************************************"
