#! /bin/sh
#
#@DEP@ libfreetype
#
# Builds and installs libftgl for the cross toolchain.
# Executed by build-uqm-dependencies.chroot

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar libftgl_URL
#
# Specifies the URL of the libftgl source tarball you want to use.
export LIBFTGL_URL="http://sourceforge.net/projects/ftgl/files/FTGL Source/2.1.3~rc5/ftgl-2.1.3-rc5.tar.bz2/download"

# Unfortunately this thing won't find freetype on its own
export CPPFLAGS="-I/usr/${HOST_TRIPLET}/include/freetype2"
export LDFLAGS="-L/usr/${HOST_TRIPLET}/lib -lfreetype"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libftgl ---"

get_tarball libftgl "${LIBFTGL_URL}" bz2

patch_source libftgl "ftgl-1-gl-m4.patch ftgl-2-obsolete-am-header.patch"

if [ ${?} -eq 10 ]
then
	echo "crossbuild_libftgl failed; could not apply patch(es)"
	exit 1
fi

# Regenerate the autohell crap after applying our patches
cd ${SRC_ROOT_DIR}/libftgl/*
./autogen.sh

autotools_build ${SRC_ROOT_DIR}/libftgl/* "--with-ft-prefix=/usr/${HOST_TRIPLET}/ --with-gl-inc=/usr/${HOST_TRIPLET}/include/ --with-gl-lib=/usr/${HOST_TRIPLET}/lib/opengl32.a"

case ${?} in
	10)
		echo "crossbuild_libftgl failed: Could not find ./configure (is libftgl source tarball sane?)"
		exit 1
		;;
	20)
		echo "crossbuild_libftgl failed: Could not find Makefile (did ./configure fail?)"
		exit 1
		;;
	*)
		;;
esac

echo "--- END: crossbuild_libftgl ---"
echo "*************************************************************************"
