#! /bin/sh
#
# Builds and installs libopus for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBOPUS_URL
#
# Specifies the URL of the libopus source tarball you want to use.
export LIBOPUS_URL="https://downloads.xiph.org/releases/opus/opus-1.1.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libopus ---"

basic_autotools_lib libopus ${LIBOPUS_URL} gz ""

echo "--- END: crossbuild_libopus ---"
echo "*************************************************************************"
