#! /bin/sh
#
# Builds and installs libfontconfig for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBFONTCONFIG_URL
#
# Specifies the URL of the libfontconfig source tarball you want to use.
export LIBFONTCONFIG_URL="https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.91.tar.bz2"

# This needs to be handed libfreetype on a silver platter.
export FREETYPE_CFLAGS="-I/usr/${HOST_TRIPLET}/include/freetype2"
export FREETYPE_LIBS="-L/usr/${HOST_TRIPLET}/lib -lfreetype"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libfontconfig ---"

basic_autotools_lib libfontconfig ${LIBFONTCONFIG_URL} bz2 ""

echo "--- END: crossbuild_libfontconfig ---"
echo "*************************************************************************"
