#! /bin/sh
#
# Builds and installs libglfw for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBGLFW_URL
#
# Specifies the URL of the libglfw tarball you want to use.
export LIBGLFW_URL="http://downloads.sourceforge.net/project/glfw/glfw/3.0.1/glfw-3.0.1.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fglfw%2F&ts=1373404138&use_mirror=iweb"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libglfw ---"

basic_cmake_lib libglfw ${LIBGLFW_URL} bz2 ""

echo "--- END: crossbuild_libglfw ---"
echo "********************************************************************************"
