#! /bin/sh
#
# Builds and installs libsfml for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBSFML_GIT_URL
#
# Specifies the URL of the libsfml git repo you want to use.
export LIBSFML_GIT_URL="https://github.com/LaurentGomila/SFML.git"

# envvar LIBSFML_GIT_HASH
#
# Specifies the libsfml git hash to build from. This does not necessarily need
# to be a hash (merely an identifier git-checkout understands), but it always
# should be a fixed hash in practice, for both security and stablility reasons.
#
# Current value is stable release 2.1
export LIBSFML_GIT_HASH="6c1899d0f70e4dc845d7f482b22c9d79f7cd4f2f"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libsfml ---"

cd ${SRC_ROOT_DIR}

git clone "${LIBSFML_GIT_URL}" libsfml-git

if [ -d libsfml-git ]; then
	cd libsfml-git
	git checkout ${LIBSFML_GIT_HASH}
else
	echo "crossbuild_libsfml failed: Could not clone/checkout libsfml git"
	exit 1
fi

cmake_build /${SRC_ROOT_DIR}/libsfml-git "-DCMAKE_FIND_ROOT_PATH=/usr/${HOST_TRIPLET}\
		-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY\
		-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY\
		-DFREETYPE_INCLUDE_DIR_freetype2=/usr/${HOST_TRIPLET}/include/freetype2\
		-DFREETYPE_INCLUDE_DIR_ft2build=/usr/${HOST_TRIPLET}/include/\
		-DFREETYPE_LIBRARY=/usr/${HOST_TRIPLET}/lib/libfreetype.dll.a\
		-DGLEW_INCLUDE_PATH=/usr/${HOST_TRIPLET}/include/GL/\
		-DGLEW_LIBRARY=/usr/${HOST_TRIPLET}/lib/libglew32.a\
		-DJPEG_INCLUDE_DIR=/usr/${HOST_TRIPLET}/include\
		-DJPEG_LIBRARY=/usr/${HOST_TRIPLET}/lib/libjpeg.dll.a\
		-DOPENAL_INCLUDE_DIR=/usr/${HOST_TRIPLET}/include/AL/\
		-DOPENAL_LIBRARY=/usr/${HOST_TRIPLET}/lib/libOpenAL32.dll.a\
		-DSNDFILE_INCLUDE_DIR=/usr/${HOST_TRIPLET}/include\
		-DSNDFILE_LIBRARY=/usr/${HOST_TRIPLET}/lib/libsndfile.dll.a"
case ${?} in
	10)
		echo "crossbuild_libsfml failed: Could not find CMakeLists.txt"
		echo "(is libsfml git hash/repo sane?)"
		return 1
		;;
	20)
		echo "crossbuild_libsfml failed: Could not find Makefile"
		echo "(did cmake fail?)"
		return 1
		;;
	*)
		return 0
		;;
esac

echo "--- END: crossbuild_libsfml ---"
echo "*************************************************************************"
