#! /bin/sh
#
# Builds and installs libsdl for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBSDL_URL
#
# Specifies the URL of the libsdl source tarball you want to use.
export LIBSDL_URL="https://www.libsdl.org/release/SDL-1.2.15.tar.gz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libsdl ---"

basic_autotools_lib libsdl "${LIBSDL_URL}" gz ""

echo "--- END: crossbuild_libsdl ---"
echo "*************************************************************************"
