#! /bin/sh
#
# Builds and installs libopenal for the cross toolchain.

# Include our common functions
. /usr/lib/crossbuild/crossbuild.subr

# envvar LIBOPENAL_URL
#
# Specifies the URL of the libopenal tarball you want to use.
export LIBOPENAL_URL="http://kcat.strangesoft.net/openal-releases/openal-soft-1.15.1.tar.bz2"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libopenal ---"

basic_cmake_lib libopenal ${LIBOPENAL_URL} bz2 ""

echo "--- END: crossbuild_libopenal ---"
echo "*************************************************************************"
