#! /bin/sh
#
# Builds and installs zlib for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# zlib uses old autoconf and therefore does not know about our cross compilation
# environment. We therefore need to let our cross toolchain override native build
# components in $PATH.
export PATH=/usr/${HOST_TRIPLET}/bin:${PATH}

echo "--- BEGIN: crossbuild_zlib ---"

cd /tmp

wget --output-document=/tmp/zlib.tar.gz ${ZLIB_URL}

if [ -f zlib.tar.gz ]; then

	if [ ! -d zlib ]; then 
		mkdir zlib
	fi

	tar -zxf zlib.tar.gz -C zlib
	cd zlib/zlib*
else
	echo "crossbuild_zlib failed: Could not get/extract zlib source"
	exit 1
fi

if [ -f win32/Makefile.gcc ]; then
	make -f win32/Makefile.gcc clean
	make -f win32/Makefile.gcc
#	make install
else
	echo "crossbuild_zlib failed: Could not find Makefile (is the zlib source tarball sane?)"
	exit 1
fi

echo "--- END: crossbuild_zlib ---"