#! /bin/sh
#
# Builds and installs libjpeg for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# envvar LIBJPEG_URL
#
# Specifies the URL of the libjpeg source tarball you want to use.
export LIBJPEG_URL="http://www.ijg.org/files/jpegsrc.v9.tar.gz"

echo "***********************************************************************************************"
echo "--- BEGIN: crossbuild_libjpeg ---"

cd /tmp

wget --output-document=/tmp/libjpeg.tar.gz ${LIBJPEG_URL}

if [ -f libjpeg.tar.gz ]; then

	if [ ! -d libjpeg ]; then 
		mkdir libjpeg
	fi

	tar -zxf libjpeg.tar.gz -C libjpeg
	cd libjpeg/libjpeg*
else
	echo "crossbuild_libjpeg failed: Could not get/extract libjpeg source"
	exit 1
fi

if [ -f configure ]; then
	./configure\
		--host=${HOST_TRIPLET}\
		--build=i686-linux-gnu\
		--prefix=/usr/${HOST_TRIPLET}
else
	echo "crossbuild_libjpeg failed: Could not find ./configure (is libjpeg source tarball sane?)"
	exit 1
fi

if [ -f Makefile ]; then
	make clean
	make
	make install
else
	echo "crossbuild_libjpeg failed: Could not find Makefile (did ./configure fail?)"
	exit 1
fi

echo "--- END: crossbuild_libjpeg ---"
echo "***********************************************************************************************"
