#! /bin/sh
#
# Builds and installs zlib for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# envvar ZLIB_URL
#
# Specifies the URL of the zlib source tarball you want to use.
export ZLIB_URL="http://zlib.net/zlib-1.2.8.tar.gz"

# zlib uses old autoconf and therefore does not know about our cross compilation
# environment. We therefore need to let our cross toolchain override native build
# components in $PATH.
export PATH=/usr/${HOST_TRIPLET}/bin:${PATH}

echo "***********************************************************************************************"
echo "--- BEGIN: crossbuild_zlib ---"

cd /tmp

wget --output-document=/tmp/zlib.tar.gz ${ZLIB_URL}

if [ -f zlib.tar.gz ]; then

	if [ ! -d zlib ]; then 
		mkdir zlib
	fi

	tar -zxf zlib.tar.gz -C zlib
	cd zlib/zlib*
else
	echo "crossbuild_zlib failed: Could not get/extract zlib source"
	exit 1
fi

if [ -f win32/Makefile.gcc ]; then
	echo "Running zlib's ./configure to trick it into making us a zlib.pc"
	./configure --prefix=/usr/${HOST_TRIPLET}

	make -f win32/Makefile.gcc clean
	make -f win32/Makefile.gcc
	ranlib *.a

	echo "Installing *.exe"
	install *.exe   /usr/${HOST_TRIPLET}/bin/

	echo "Installing *.dll"
	install *.dll   /usr/${HOST_TRIPLET}/bin/

#	echo "Installing *.lib"
#	cp *.lib   /usr/${HOST_TRIPLET}/lib

	echo "Installing *.a"
	install *.a    /usr/${HOST_TRIPLET}/lib/

	echo "Installing *.h"
	install *.h     /usr/${HOST_TRIPLET}/include/
	
	echo "Installing zlib.pc"
	install -D zlib.pc /usr/${HOST_TRIPLET}/lib/pkgconfig/zlib.pc
else
	echo "crossbuild_zlib failed: Could not find Makefile (is the zlib source tarball sane?)"
	exit 1
fi

echo "--- END: crossbuild_zlib ---"
echo "***********************************************************************************************"
