#! /bin/sh
#@DEP@ zlib
#
# Builds and installs libpng for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# envvar LIBPNG_URL
#
# Specifies the URL of the libpng source tarball you want to use.
export LIBPNG_URL="ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.11.tar.xz"

echo "*************************************************************************"
echo "--- BEGIN: crossbuild_libpng ---"

cd /tmp

wget --output-document=/tmp/libpng.tar.xz ${LIBPNG_URL}

if [ -f libpng.tar.xz ]; then

	if [ ! -d libpng ]; then 
		mkdir libpng
	fi

	tar -Jxf libpng.tar.xz -C libpng
	cd libpng/libpng*
else
	echo "crossbuild_libpng failed: Could not get/extract libpng source"
	exit 1
fi

if [ -f configure ]; then
	./configure\
		--host=${HOST_TRIPLET}\
		--build=i686-linux-gnu\
		--prefix=/usr/${HOST_TRIPLET}
else
	echo "crossbuild_libpng failed: Could not find ./configure (is libpng source tarball sane?)"
	exit 1
fi

if [ -f Makefile ]; then
	make clean
	make
	make install
else
	echo "crossbuild_libpng failed: Could not find Makefile (did ./configure fail?)"
	exit 1
fi

echo "--- END: crossbuild_libpng ---"
echo "*************************************************************************"
