#! /bin/sh
#@DEP@ libogg
#
# Builds and installs libtheora for the cross toolchain.
# Sourced from build-uqm-dependencies.chroot

# envvar LIBTHEORA_URL
#
# Specifies the URL of the libtheora source tarball you want to use.
export LIBTHEORA_URL="http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz"

echo "***********************************************************************************************"
echo "--- BEGIN: crossbuild_libtheora ---"

cd /tmp

wget --output-document=/tmp/libtheora.tar.gz ${LIBTHEORA_URL}

if [ -f libtheora.tar.gz ]; then

	if [ ! -d libtheora ]; then 
		mkdir libtheora
	fi

	tar -zxf libtheora.tar.gz -C libtheora
	cd libtheora/libtheora*
	pwd
else
	echo "crossbuild_libtheora failed: Could not get/extract libtheora source"
	exit 1
fi

if [ -f configure ]; then
	./configure\
		--host=${HOST_TRIPLET}\
		--build=i686-linux-gnu\
		--prefix=/usr/${HOST_TRIPLET}
else
	echo "crossbuild_libtheora failed: Could not find ./configure (is libtheora source tarball sane?)"
	exit 1
fi

if [ -f Makefile ]; then
	make clean
	make
	make install
else
	echo "crossbuild_libtheora failed: Could not find Makefile (did ./configure fail?)"
	exit 1
fi

echo "--- END: crossbuild_libtheora ---"
echo "***********************************************************************************************"
