#! /bin/bash
#
# This script perpetrates various terrifyingly ugly acts of kludgery against
# the cross toolchain so UQM will find all the libs it needs. Please, please
# do not use this script if you don't intend to build UQM with the live system.

# libogg and libvorbis install as e.g. 'libvorbisfile.dll.a', when UQM looks for
# 'vorbisfile.dll.a', we need to correct this.
ln -s /usr/${HOST_TRIPLET}/libogg.lib			/usr/${HOST_TRIPLET}/ogg.lib
ln -s /usr/${HOST_TRIPLET}/libogg_d.lib			/usr/${HOST_TRIPLET}/ogg_d.lib
ln -s /usr/${HOST_TRIPLET}/libogg_static.lib		/usr/${HOST_TRIPLET}/ogg_static.lib
ln -s /usr/${HOST_TRIPLET}/libogg_static_d.lib		/usr/${HOST_TRIPLET}/ogg_static_d.lib

ln -s /usr/${HOST_TRIPLET}/libvorbis.lib		/usr/${HOST_TRIPLET/vorbis.lib
ln -s /usr/${HOST_TRIPLET}/libvorbis_d.lib		/usr/${HOST_TRIPLET}/vorbis_d.lib
ln -s /usr/${HOST_TRIPLET}/libvorbis_static.lib		/usr/${HOST_TRIPLET}/vorbis_static.lib
ln -s /usr/${HOST_TRIPLET}/libvorbis_static_d.lib	/usr/${HOST_TRIPLET}/vorbis_static_d.lib

ln -s /usr/${HOST_TRIPLET}/libvorbisfile.lib		/usr/${HOST_TRIPLET}/vorbisfile.lib
ln -s /usr/${HOST_TRIPLET}/libvorbisfile_d.lib		/usr/${HOST_TRIPLET}/vorbisfile_d.lib
ln -s /usr/${HOST_TRIPLET}/libvorbisfile_static.lib	/usr/${HOST_TRIPLET}/vorbisfile_static.lib
ln -s /usr/${HOST_TRIPLET}/libvorbisfile_static_d.lib	/usr/${HOST_TRIPLET}/vorbisfile_static_d.lib
