#!/bin/sh
set -v # ideally it'll be hard to miss the symlinks being removed below

rm -f config/includes.chroot/usr/bin/build-uqm-dependencies.sh config/includes.chroot/usr/bin/toolchain-ugly-hacks.sh
rm -f config/package-list/live.list.chroot

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
