#!/bin/sh

# envvar DEBIAN_MIRROR
# The URL of the Debian mirror to get packages from.
export DEBIAN_MIRROR="ftp://ftp.egr.msu.edu/debian"

lb config noauto \
	--apt-options "-y --force-yes"\
	--apt-recommends false\
	--distribution wheezy\
	-k 486\
	--architecture i386\
	--mirror-bootstrap ${DEBIAN_MIRROR}\
	--mirror-binary ${DEBIAN_MIRROR}\
	--bootappend-live "boot=live config hostname=uqm-crossbuilder username=fwiffo"\
	"${@}"
